apiVersion: v1
kind: Service
metadata:
  labels:
    app: bitcoin
    environment: test
  name: bitcoin
  namespace: sirius-nodes
#  annotations:
#    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 8332
  selector:
    app: nginx-proxy-a
  sessionAffinity: None
  type: ClusterIP
#  type: LoadBalancer
