apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Litecoin Swisschain Private Network Explorer
  labels:
    app: litecoin-swisschain-private
    environment: Development
    tier: Service
  name: litecoin-swisschain-private
  namespace: sirius-explorers
spec:
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: litecoin-swisschain-private
  template:
    metadata:
      labels:
        app: litecoin-swisschain-private
      name: litecoin-swisschain-private
    spec:
      containers:
      - name: litecoin-swisschain-private
        image: oktapodia/btc-rpc-explorer
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command:
             - /bin/sh
             - -c 
             - "/bin/echo 'options single-request-reopen' >> /etc/resolv.conf"
        ports:
        - containerPort: 5000
        - containerPort: 5001
        readinessProbe:
          httpGet:
            path: /
            port: 3002
          initialDelaySeconds: 40
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3002
          initialDelaySeconds: 40
          periodSeconds: 20
        resources:
          requests:
            memory: 64Mi 
            cpu: 40m 
          limits:
            memory: 128Mi 
            cpu: 500m 
        env:
        - name: RPC_USER
          valueFrom:
            secretKeyRef:
              name: litecoin-swisschain-private
              key: LITECOIN_RPC_USER
        - name: LITECOIN_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: litecoin-swisschain-private
              key: LITECOIN_RPC_PASS
        - name: RPC_HOST 
          value: "litecoin-private.sirius-nodes.svc.cluster.local"
        - name: RPC_PORT
          value: "80"