apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: rabbit
    environment: dev
  name: rabbit
  namespace: sirius
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: rabbit
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rabbit
        name: rabbit
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_VHOST
          value: /
        image: rabbitmq:3.6.16-management
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: 5672
          timeoutSeconds: 1
        name: rabbit
        ports:
        - containerPort: 5672
          protocol: TCP
        - containerPort: 15672
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/rabbitmq/mnesia
          name: rabbit
        - mountPath: /etc/rabbitmq/rabbitmq-env.conf
          name: rabbit-sirius-conf
          readOnly: true
          subPath: rabbitmq-env.conf
        - mountPath: /etc/rabbitmq/definitions.json
          name: rabbit-sirius-conf
          readOnly: true
          subPath: definitions.json
        - mountPath: /etc/rabbitmq/enabled_plugins
          name: rabbit-sirius-conf
          subPath: enabled_plugins
          readOnly: true
      volumes:
      - name: rabbit
        azureDisk:
          kind: Managed
          diskName: rabbit-sirius
          diskURI: /subscriptions/86ba7b87-cc6d-4e1a-9c1d-81aa62cd027a/resourceGroups/Kubernetes-ShowRoom-RG/providers/Microsoft.Compute/disks/rabbit-sirius
      - configMap:
          defaultMode: 420
          name: rabbit
        name: rabbit-sirius-conf
      dnsPolicy: ClusterFirst
      nodeSelector:
        type: Services
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
