apiVersion: v1
kind: Service
metadata:
  labels:
    app: indexer-2-worker
    environment: Development
  name: indexer-2-worker
  namespace: sirius-indexers
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: indexer-2-worker
  sessionAffinity: None
  type: ClusterIP
