apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: Lykke Logs
  labels:
    app: seq
    environment: dev
  name: seq
  namespace: monitoring
spec:
  revisionHistoryLimit: 5
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: seq
      name: seq
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      nodeSelector:
         type: Monitoring-1
#      nodeSelector:
#        kubernetes.io/hostname: k8s-test-p-node-3
      containers:
      - name: seq
        image: datalust/seq:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: ACCEPT_EULA
            value: "Y"
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
#            ephemeral-storage: 512Mi
          limits:
            memory: 1500Mi
            cpu: 200
#            ephemeral-storage: 512Mi
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: seq-data
          mountPath: /data

      volumes:
      - name: seq-data
        azureDisk:
          kind: Managed
          diskName: seq-data
          diskURI: /subscriptions/86ba7b87-cc6d-4e1a-9c1d-81aa62cd027a/resourceGroups/Kubernetes-ShowRoom-RG/providers/Microsoft.Compute/disks/seq-data

#        volumeMounts:
#        - name: mongodb-test
#          mountPath: /data/db
#          name: mongodata
#      volumes:
#      - hostPath:
#          path: /mnt/Mongodb-test
#          type: Directory
#        name: mongodata

