apiVersion: v1
kind: Service
metadata:
  name: seq
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 12201
      protocol: "UDP"
      targetPort: 12201
      name: udp
    - port: 80
      protocol: "TCP"
      targetPort: 80
      name: http
  selector:
    app: seq
