apiVersion: v1
kind: Service
metadata:
  labels:
    app: indexer-1
    environment: Development
  name: indexer-1
  namespace: sirius-indexers
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  - name: grpc
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: indexer-1
  sessionAffinity: None
  type: ClusterIP
