apiVersion: v1
data:
  default.conf: |
    #proxy_buffers   4 256k;
    #proxy_busy_buffers_size   256k;
    server_names_hash_bucket_size 128;
    #chunked_transfer_encoding     off;
    client_max_body_size          50M;
    fastcgi_read_timeout          300;
    proxy_connect_timeout         300;
    proxy_send_timeout            300;
    proxy_read_timeout            300;
    send_timeout                  300;

    server {
        listen 81;
        access_log off;
        error_log off;

        location /probe {
            set_by_lua $env_info_cnt 'return os.getenv("ENV_INFO")';
            return 200 '{"Env": "$env_info_cnt"}';
        }
        location /stat {
            stub_status on;
        }
    }

  nginx.conf: |

    user  nginx;
    worker_processes  2;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    env ENV_INFO;

    load_module modules/ngx_stream_module.so;
    load_module modules/ndk_http_module.so;
    load_module modules/ngx_http_lua_module.so;

    events {
        worker_connections  10240;
    }

    stream {
        include /etc/nginx/conf.d/*.stream;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }

  headers.conf: |
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection keep-alive;
    proxy_set_header   Host $host;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header        X-Real-IP       $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;

  #resolv.conf: |
  #  nameserver 10.112.0.10
  #  search default.svc.cluster.local svc.cluster.local cluster.local
  #  options ndots:5

  default.stream: |
    # portal.universe
    server {
      listen 120;
      proxy_pass portal.universe:80;
    }
    # portal.universe
    server {
      listen 120;
      proxy_pass portal.universe:80;
    }
    # api.universe
    server {
      listen 110;
      proxy_pass api.universe:80;
    }
    # api.sirius
    server {
      listen 100;
      proxy_pass api.sirius:80;
    }
    # bitcoin-regtest.sirius-nodes
    server {
      listen 18443;
      proxy_pass 138.201.119.59:18443;
    }

    # bitcoin-test.sirius-nodes
    server {
      listen 8041;
      proxy_pass 51.137.113.82:18443;
    }

    # ethereum-ropsten.sirius-nodes
    server {
      listen 8545;
      proxy_pass 138.201.89.196:8545;
    }

    # bitcoin.sirius-nodes
    server {
      listen 8332;
      proxy_pass 104.45.43.60:8332;
    }

    # ethereum.sirius-nodes
    server {
      listen 8000;
      proxy_pass 94.130.210.71:8000;
    }

    # stellar-test.sirius-nodes
    server {
      listen 8020;
      proxy_pass 144.76.25.187:8020;
    }

    # litecoin-private.sirius-nodes
    server {
      listen 8045;
      proxy_pass 144.76.25.187:8045;
    }

kind: ConfigMap
metadata:
  name: nginx-proxy-a-conf
  namespace: sirius-nodes
