apiVersion: v1
kind: Service
metadata:
  labels:
    app: bitcoin-swisschain-private
    environment: dev
  name: bitcoin-swisschain-private
  namespace: sirius-explorers
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 3002
  selector:
    app: bitcoin-swisschain-private
  sessionAffinity: None
  type: ClusterIP
#  type: LoadBalancer
