apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-panel
    environment: Development
  name: admin-panel
  namespace: universe
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: admin-panel
  sessionAffinity: None
  type: ClusterIP
